//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokuFlex.FileSync {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DokuFlex.FileSync.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileSync Preview.
        /// </summary>
        internal static string ApplicationTitleText {
            get {
                return ResourceManager.GetString("ApplicationTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials changed successfully.
        /// </summary>
        internal static string ChangeCredentialsSuccessfullyText {
            get {
                return ResourceManager.GetString("ChangeCredentialsSuccessfullyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change crendentials....
        /// </summary>
        internal static string ChangeCredentialsText {
            get {
                return ResourceManager.GetString("ChangeCredentialsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string ExitText {
            get {
                return ResourceManager.GetString("ExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginEmailAddress.
        /// </summary>
        internal static string LoginEmailAddressKey {
            get {
                return ResourceManager.GetString("LoginEmailAddressKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginPassword.
        /// </summary>
        internal static string LoginPasswordKey {
            get {
                return ResourceManager.GetString("LoginPasswordKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open your folder.
        /// </summary>
        internal static string OpenYourFolderText {
            get {
                return ResourceManager.GetString("OpenYourFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Pause.
        /// </summary>
        internal static string PauseText {
            get {
                return ResourceManager.GetString("PauseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Resume.
        /// </summary>
        internal static string ResumeText {
            get {
                return ResourceManager.GetString("ResumeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select directory....
        /// </summary>
        internal static string SelectSyncDirectoryText {
            get {
                return ResourceManager.GetString("SelectSyncDirectoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;ettings.
        /// </summary>
        internal static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source folder is not set..
        /// </summary>
        internal static string SourceFolderNoSetText {
            get {
                return ResourceManager.GetString("SourceFolderNoSetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Stop syncing a community.
        /// </summary>
        internal static string StopSyncingAFolderText {
            get {
                return ResourceManager.GetString("StopSyncingAFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Sync a new community.
        /// </summary>
        internal static string SyncANewFolderText {
            get {
                return ResourceManager.GetString("SyncANewFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization completed!.
        /// </summary>
        internal static string SyncCompleteTipText {
            get {
                return ResourceManager.GetString("SyncCompleteTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The synchronization directory is not set..
        /// </summary>
        internal static string SyncDirectoryNotSetText {
            get {
                return ResourceManager.GetString("SyncDirectoryNotSetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncDirectoryPath.
        /// </summary>
        internal static string SyncDirectoryPathKey {
            get {
                return ResourceManager.GetString("SyncDirectoryPathKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync &amp;now.
        /// </summary>
        internal static string SyncNowText {
            get {
                return ResourceManager.GetString("SyncNowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync started!.
        /// </summary>
        internal static string SyncStartedTipText {
            get {
                return ResourceManager.GetString("SyncStartedTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error conflict.
        /// </summary>
        internal static string SyncStatusErrorConflict {
            get {
                return ResourceManager.GetString("SyncStatusErrorConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In sync.
        /// </summary>
        internal static string SyncStatusInSync {
            get {
                return ResourceManager.GetString("SyncStatusInSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string SyncStatusPending {
            get {
                return ResourceManager.GetString("SyncStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync in progress.
        /// </summary>
        internal static string SyncStatusSyncInProgress {
            get {
                return ResourceManager.GetString("SyncStatusSyncInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization status.
        /// </summary>
        internal static string SyncStatusText {
            get {
                return ResourceManager.GetString("SyncStatusText", resourceCulture);
            }
        }
    }
}
