//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokuFlex.Scan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DokuFlex.Scan.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error mientras se procesaba la acción..
        /// </summary>
        internal static string AsyncTaskError {
            get {
                return ResourceManager.GetString("AsyncTaskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error mientras se creaban los archivos .tiff de multiples paginas..
        /// </summary>
        internal static string CreateMultipageTiffError {
            get {
                return ResourceManager.GetString("CreateMultipageTiffError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo documental no es valido..
        /// </summary>
        internal static string InvalidDocumentaryTypeError {
            get {
                return ResourceManager.GetString("InvalidDocumentaryTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La carpeta de destino de la digitalización no es valida..
        /// </summary>
        internal static string InvalidFolderError {
            get {
                return ResourceManager.GetString("InvalidFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo acceder a las paletas de colores disponibles del escanner seleccionado..
        /// </summary>
        internal static string InvalidPixelFormat {
            get {
                return ResourceManager.GetString("InvalidPixelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del perfil no es correcto..
        /// </summary>
        internal static string InvalidProfileNameError {
            get {
                return ResourceManager.GetString("InvalidProfileNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Resolución (PPP) no es valida..
        /// </summary>
        internal static string InvalidResolutionError {
            get {
                return ResourceManager.GetString("InvalidResolutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El escáner no es valido..
        /// </summary>
        internal static string InvalidScannerError {
            get {
                return ResourceManager.GetString("InvalidScannerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo acceder a las paletas de colores disponibles del escanner seleccionado..
        /// </summary>
        internal static string PixelsNotAviableError {
            get {
                return ResourceManager.GetString("PixelsNotAviableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo acceder a las resoluciones disponibles del escanner seleccionado..
        /// </summary>
        internal static string ResolutionsNotAviableError {
            get {
                return ResourceManager.GetString("ResolutionsNotAviableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo establecer comunicación con el escáner seleccionado..
        /// </summary>
        internal static string ScannerCannotByActivate {
            get {
                return ResourceManager.GetString("ScannerCannotByActivate", resourceCulture);
            }
        }
    }
}
