//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokuFlex.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DokuFlex.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoSync.
        /// </summary>
        internal static string AutoSync {
            get {
                return ResourceManager.GetString("AutoSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new folder on {0}?{1} Click No to create a root folder instead..
        /// </summary>
        internal static string CreateNewFolderText {
            get {
                return ResourceManager.GetString("CreateNewFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language changed. Reopen the program to changed take effect.
        /// </summary>
        internal static string LanguageChangedText {
            get {
                return ResourceManager.GetString("LanguageChangedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading folders... wait..
        /// </summary>
        internal static string LoadingFoldersText {
            get {
                return ResourceManager.GetString("LoadingFoldersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginUserName.
        /// </summary>
        internal static string LoginEmailAddressKey {
            get {
                return ResourceManager.GetString("LoginEmailAddressKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username and/or password is not valid..
        /// </summary>
        internal static string LoginFailedText {
            get {
                return ResourceManager.GetString("LoginFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loging with {0}.
        /// </summary>
        internal static string LogingWithCredentialsText {
            get {
                return ResourceManager.GetString("LogingWithCredentialsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginPassword.
        /// </summary>
        internal static string LoginPasswordKey {
            get {
                return ResourceManager.GetString("LoginPasswordKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LoginPicture {
            get {
                object obj = ResourceManager.GetObject("LoginPicture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginRemenberMyIdAndPassword.
        /// </summary>
        internal static string LoginRemenberMyIdAndPasswordKey {
            get {
                return ResourceManager.GetString("LoginRemenberMyIdAndPasswordKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder.
        /// </summary>
        internal static string NewFolderText {
            get {
                return ResourceManager.GetString("NewFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProxyDomain.
        /// </summary>
        internal static string ProxyDomainKey {
            get {
                return ResourceManager.GetString("ProxyDomainKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProxyPassword.
        /// </summary>
        internal static string ProxyPasswordKey {
            get {
                return ResourceManager.GetString("ProxyPasswordKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProxyUseProxy.
        /// </summary>
        internal static string ProxyUseProxyKey {
            get {
                return ResourceManager.GetString("ProxyUseProxyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProxyUserName.
        /// </summary>
        internal static string ProxyUserNameKey {
            get {
                return ResourceManager.GetString("ProxyUserNameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestServiceUrl.
        /// </summary>
        internal static string RestServiceUrlKey {
            get {
                return ResourceManager.GetString("RestServiceUrlKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncHour.
        /// </summary>
        internal static string SyncHour {
            get {
                return ResourceManager.GetString("SyncHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncInterval.
        /// </summary>
        internal static string SyncInterval {
            get {
                return ResourceManager.GetString("SyncInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UILanguage.
        /// </summary>
        internal static string UILanguageKey {
            get {
                return ResourceManager.GetString("UILanguageKey", resourceCulture);
            }
        }
    }
}
