//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokuSign {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DokuSign.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error en el procesamiento de la solicitud..
        /// </summary>
        internal static string ApplicationError {
            get {
                return ResourceManager.GetString("ApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El certificado no es valido..
        /// </summary>
        internal static string CertificateNoValidError {
            get {
                return ResourceManager.GetString("CertificateNoValidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La carpeta de destino no es valida..
        /// </summary>
        internal static string DestinationFolderNoValidError {
            get {
                return ResourceManager.GetString("DestinationFolderNoValidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo abrir el certificado. Asegurese de que la ruta y/o contraseña son correcta..
        /// </summary>
        internal static string OpenCertificateError {
            get {
                return ResourceManager.GetString("OpenCertificateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña no puede estar en blanco..
        /// </summary>
        internal static string PasswordNoValidError {
            get {
                return ResourceManager.GetString("PasswordNoValidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de firma digital no es valido..
        /// </summary>
        internal static string SigFileWithNoValidError {
            get {
                return ResourceManager.GetString("SigFileWithNoValidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La pocisión de la firma no ha sido establecida..
        /// </summary>
        internal static string SigImageNoSaveCorrdinatesError {
            get {
                return ResourceManager.GetString("SigImageNoSaveCorrdinatesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La firma no es valida..
        /// </summary>
        internal static string SigImageNoValidError {
            get {
                return ResourceManager.GetString("SigImageNoValidError", resourceCulture);
            }
        }
    }
}
